---
version: 2

sphinx:
  builder: "html"
  configuration: "docs/source/conf.py"
  fail_on_warning: false

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: "docs/requirements.txt"
    - method: "pip"
      path: "."
