---
extends: "default"
rules:
<<<<<<< HEAD
  comments: "enable"
=======
  comments:
    min-spaces-from-content: 1
>>>>>>> c5f3eb1 (Cookie initialy baked by NetworkToCode Cookie Drift Manager Tool)
  empty-values: "enable"
  indentation:
    indent-sequences: "consistent"
  line-length: "disable"
  quoted-strings:
    quote-type: "double"
<<<<<<< HEAD
=======
ignore: |
  .venv/
>>>>>>> c5f3eb1 (Cookie initialy baked by NetworkToCode Cookie Drift Manager Tool)
