---
name: "CI (non-template jobs)"
on:
  push:
    branches:
      - main
      - develop
  pull_request: ~
jobs:
  validate_renovate:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Validate renovate configuration"
        uses: "rinchsan/renovate-config-validator@v0.0.11"
        with:
          pattern: "renovate.json"
  mypy:
    runs-on: "ubuntu-20.04"
    env:
      INVOKE_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v1"
      - name: "Linting: flake8"
        run: "poetry run invoke mypy"
